spring:
  application:
    name: pharmacy-assistant
  datasource:
    url: jdbc:postgresql://localhost:5433/pharmacyIA
    username: postgres
    password: 280776

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info