spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacy
    username: pharmacy
    password: pharmacy
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info